### ISSUE TITLE
`.isPreferentialGauge` attribute is bugged

### ISSUE THREAD

**Issue by gosuto-inzasheru** [balancer/gauges-subgraph#94]
can be replicated with the following query:
```
query MyQuery {
  pools(where: {poolId: "0xdedb11a6a23263469567c2881a9b9f8629ee0041000000000000000000000669"}) {
    preferentialGauge {
      poolId
      isKilled
      isPreferentialGauge
      id
    }
  }
}
```
which returns:
```
{
  "data": {
    "pools": [
      {
        "preferentialGauge": {
          "poolId": "0xdedb11a6a23263469567c2881a9b9f8629ee0041000000000000000000000669",
          "isKilled": false,
          "isPreferentialGauge": false,
          "id": "0xd98ed0426d18b115d6388923803e33ad8aaf11f8"
        }
      }
    ]
  }
}
```

this looks wrong to me; how can a pool have a preferential gauge entry but that preferential gauge having `isPreferentialGauge` as false?

imo if `preferentialGauge` comes back as anything but `null`, `isPreferentialGauge` should be true

note that this is also problematic on other objects such as `liquidityGauges`, where there is no `preferentialGauge` attribute available (only `isPreferentialGauge`)

this was found on mainnet, not sure if this is the case for other chains as well

**Comment by mendesfabio** [comment]
hey @gosuto-inzasheru that's indeed a bug, thanks for reporting! I've verified all other chains but it only happened on Mainnet. It's an edge-case because now preferential gauges can be set via `EventEmitter` but before the only way to do it was adding the gauge to the `GaugeController` -- more details in the attached PR. Fix has been deployed to staging and should be live in production soon.

**Comment by mendesfabio** [comment]
merged to prod! the [query](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-gauges/graphql?query=query+MyQuery+%7B%0A++pools(where:+%7BpoolId:+%220xdedb11a6a23263469567c2881a9b9f8629ee0041000000000000000000000669%22%7D)+%7B%0A++++preferentialGauge+%7B%0A++++++poolId%0A++++++isKilled%0A++++++isPreferentialGauge%0A++++++id%0A++++%7D%0A++%7D%0A%7D) you shared is working as expected.
